services:
  - type: web
    name: xyz-consulting
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/xyz-consulting-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17